### ISSUE TITLE
Error 429 on Spectragram Demo Site

### ISSUE THREAD

**Issue by tommusrhodus** [adrianengine/jquery-spectragram#48]
### Expected behavior

Instagram feeds showing on demo site: http://spectragram.js.org

### Actual behavior

Instagram feeds not showing due to API change, error 429 for each in console.

### Steps to reproduce this behavior

View Demo Site. Also note that after registering a new client ID and Access Token to get past the 429 error in a local install, I'm presented with the following JS error.

![screen shot 2016-06-01 at 20 52 08](https://cloud.githubusercontent.com/assets/3149464/15723526/ba98f530-283a-11e6-8e04-05ab9ac83ed4.png)

Hope this helps in any way mate!

**Comment by adrianengine** [comment]
Hi @tommusrhodus !

On June 1, Instagram, which is owned by Facebook, [will stop allowing many third parties to access the images in its feeds](http://techcrunch.com/2015/11/17/just-instagram/).

This means you will no longer be able to fetch photos with spectragram after May 31.

I will see if there is something i can do, maybe a rebrand because the word "gram" is in the name of the plugin and is not allowed by terms of Instagram.

Thank you!

**Comment by reinaris** [comment]
@adrianengine thats bad news! Thats why my feed isn't working anymore.. any solutions to this issue?

**Comment by adrianengine** [comment]
Hi guys!
Please have a read at this: [https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

You can make it work again!

**Comment by reinaris** [comment]
@adrianengine thanks mate for all the work and the perfect documentation about it!
I created a fresh client on Instagram, did the access token trick and js isnt throwing any errors. So thats good but the result of the request is `This user account is private or doesn't have any photos.`.
The account isn't private and I got 4 posts out there.

Any ideas on this?

**Comment by adrianengine** [comment]
Hi @reinaris 
Please provide me with some [codepen](http://codepen.io/pen) or [jsfiddle](https://jsfiddle.net/) to take a look on that behaviour.

Also you can check [this example](http://codepen.io/adrianengine/pen/ONwbmQ) on codepen.

Maybe the reason you get that message is because the user you are trying to get photos has not granted you permissions to your app on sandbox mode.

**Comment by tommusrhodus** [comment]
If it helps anyone here, we also wrote an article and some videos about how to create the updated client ID and token needed, it's a matter of refreshing permissions basically: https://tommusrhodus.ticksy.com/article/7566/
